import { useState } from 'react';
import Markdown from 'react-markdown';
import { generatePYQs } from '../gemini';
import { syllabus, subjects } from '../syllabus';
import { Loader2, HelpCircle, CheckCircle2 } from 'lucide-react';

export default function Practice() {
  const [subject, setSubject] = useState("");
  const [chapter, setChapter] = useState("");
  const [topic, setTopic] = useState("");
  const [loading, setLoading] = useState(false);
  const [questions, setQuestions] = useState<any[]>([]);
  const [error, setError] = useState("");

  const chapters = subject ? Object.keys(syllabus[subject]) : [];
  const topics = subject && chapter ? syllabus[subject][chapter] : [];

  const handleGenerate = async () => {
    if (!subject || !chapter || !topic) {
      setError("Please select subject, chapter, and topic.");
      return;
    }
    setError("");
    setLoading(true);
    setQuestions([]);
    try {
      const data = await generatePYQs(subject, chapter, topic);
      setQuestions(data || []);
    } catch (err) {
      setError("Failed to generate PYQs. Please ensure your Gemini API key is configured.");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-6 md:p-10 max-w-5xl mx-auto">
      <div className="mb-10">
        <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-3">Practice PYQs</h1>
        <p className="text-gray-600 text-lg">
          Select a topic to get previous year questions strictly from JEE Mains & Advanced exams, generated by AI.
        </p>
      </div>

      <div className="bg-white rounded-2xl shadow-[0_2px_8px_rgba(0,0,0,0.04)] p-6 mb-10 border border-gray-100 flex flex-col md:flex-row gap-4 items-end">
        <div className="flex-1 w-full relative">
          <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Subject</label>
          <select 
            value={subject} 
            onChange={(e) => { setSubject(e.target.value); setChapter(""); setTopic(""); }}
            className="w-full bg-gray-50 border border-gray-200 text-gray-900 rounded-xl px-4 py-3 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 transition-all appearance-none"
          >
            <option value="">Select Subject</option>
            {subjects.map(s => <option key={s} value={s}>{s}</option>)}
          </select>
        </div>
        <div className="flex-1 w-full relative">
          <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Chapter</label>
          <select 
            value={chapter} 
            onChange={(e) => { setChapter(e.target.value); setTopic(""); }}
            disabled={!subject}
            className="w-full bg-gray-50 border border-gray-200 text-gray-900 rounded-xl px-4 py-3 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 transition-all appearance-none disabled:opacity-50"
          >
            <option value="">Select Chapter</option>
            {chapters.map(c => <option key={c} value={c}>{c}</option>)}
          </select>
        </div>
        <div className="flex-1 w-full relative">
          <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Topic</label>
          <select 
            value={topic} 
            onChange={(e) => setTopic(e.target.value)}
            disabled={!chapter}
            className="w-full bg-gray-50 border border-gray-200 text-gray-900 rounded-xl px-4 py-3 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 transition-all appearance-none disabled:opacity-50"
          >
            <option value="">Select Topic</option>
            {topics.map(t => <option key={t} value={t}>{t}</option>)}
          </select>
        </div>
        <button 
          onClick={handleGenerate}
          disabled={loading || !topic}
          className="w-full md:w-auto px-8 py-3 bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 text-white font-medium rounded-xl transition-colors shadow-sm whitespace-nowrap flex items-center justify-center gap-2"
        >
          {loading ? <Loader2 className="animate-spin" size={20} /> : 'Generate PYQs'}
        </button>
      </div>

      {error && (
        <div className="p-4 bg-red-50 text-red-700 rounded-xl mb-8 border border-red-100">
          {error}
        </div>
      )}

      {questions.length > 0 && (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
          {questions.map((q, idx) => (
            <QuestionCard key={idx} question={q} index={idx} />
          ))}
        </div>
      )}
    </div>
  );
}

function QuestionCard({ question, index }: { question: any, index: number }) {
  const [showSolution, setShowSolution] = useState(false);

  return (
    <div className="bg-white rounded-2xl shadow-[0_2px_8px_rgba(0,0,0,0.04)] p-6 md:p-8 border border-gray-100">
      <div className="flex items-center gap-3 mb-6">
        <span className="flex-shrink-0 w-8 h-8 rounded-full bg-indigo-100 text-indigo-700 flex items-center justify-center font-bold text-sm">
          {index + 1}
        </span>
        <span className="px-3 py-1 bg-gray-100 text-gray-600 text-xs font-semibold uppercase tracking-wider rounded-md">
          {question.exam}
        </span>
      </div>

      <div className="text-lg text-gray-800 mb-6 font-medium">
        <Markdown>{question.questionText}</Markdown>
      </div>

      {question.options && question.options.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
          {question.options.map((opt: string, i: number) => (
            <div key={i} className="p-4 border border-gray-200 rounded-xl bg-gray-50 flex gap-3 items-start">
              <span className="font-semibold text-gray-400">{String.fromCharCode(65 + i)}</span>
              <span className="text-gray-700"><Markdown>{opt}</Markdown></span>
            </div>
          ))}
        </div>
      )}

      {!showSolution ? (
        <button 
          onClick={() => setShowSolution(true)}
          className="flex items-center gap-2 text-indigo-600 font-medium hover:text-indigo-800 transition-colors"
        >
          <HelpCircle size={20} />
          Show Solution & Hint
        </button>
      ) : (
        <div className="mt-6 pt-6 border-t border-gray-100 animate-in fade-in duration-300">
          <div className="flex items-center gap-2 mb-4 text-emerald-600 font-bold">
            <CheckCircle2 size={24} />
            Correct Answer: {question.correctAnswer}
          </div>
          <div className="bg-emerald-50 rounded-xl p-6 border border-emerald-100">
            <h4 className="text-sm uppercase tracking-wider text-emerald-800 font-bold mb-2">Step-by-Step Solution</h4>
            <div className="prose prose-sm prose-emerald max-w-none text-emerald-900">
              <Markdown>{question.solution}</Markdown>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
